Repository pypiserver/pypiserver, pull requests merged in 2018-06, with the labels that each got.

#208 FIX: Fallback URL, remove calls to pip.main
  .gitignore
  CHANGES.rst
  README.rst
  bin/gen-standalone.sh
  pypiserver/__main__.py
  pypiserver/core.py
  pypiserver/manage.py
  pypiserver/welcome.html
  tests/test_app.py
  tests/test_main.py
  tests/test_server.py
Labels: type.Maintainance

#198 Drop support for EOL Python 3.3
  README.rst
  bootstrap.py
  pypiserver/__main__.py
  pypiserver/_app.py
  pypiserver/cache.py
  pypiserver/core.py
  requirements/dev.pip
  setup.py
  tests/test_app.py
  tests/test_init.py
Labels: type.Maintainance

#209 Remove broken downloads badge
  README.rst
Labels: tag.docs

#210 Dockerfile & doc updates
  .dockerignore
  .travis.yml
  AUTHORS.rst
  CHANGES.rst
  Dockerfile
  README.rst
  bin/test-docker.sh
  docker-compose.yml
Labels: type.Enhancement
